### ISSUE TITLE
程序无法运行

### ISSUE THREAD

**Issue by yinyb** [meikoz/EasyApp#3]
06-20 17:41:59.860 22651-22880/com.zhoujinlong E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                 Process: com.zhoujinlong, PID: 22651
                                                                 java.lang.NoSuchMethodError: No virtual method log(Ljava/lang/String;)V in class Lokhttp3/internal/Platform; or its super classes (declaration of 'okhttp3.internal.Platform' appears in /data/app/com.zhoujinlong-1/base.apk)
                                                                     at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:109)
                                                                     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:157)
                                                                     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                     at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by meikoz** [comment]
93682011 你加下我qq

**Comment by racofix** [comment]
将core中的build.gradle中的改成
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
compile 'com.squareup.retrofit2:adapter-rxjava:2.0.0-beta4'
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'

**Comment by zhengxiaochuan** [comment]
修改过之后还是不行啊

**Comment by racofix** [comment]
@zhengxiaochuan  compile 'com.squareup.okhttp3:logging-interceptor:3.1.2'改成这个  我昨天升级的时候出现的问题

**Comment by zhengxiaochuan** [comment]
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.0-beta4'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'
    compile 'com.squareup.okhttp3:logging-interceptor:3.1.2'
我都已经改成这样了，还是不行啊，一登录App就停止啊

**Comment by meikoz** [comment]
@zhengxiaochuan  你+我q 93682011  发给我报错信息 我看一下
